// Barrel — import all components from '@/components'
export { Nav }           from './Nav'
export { Footer }        from './Footer'
export { SplitText }     from './SplitText'
export { MagneticBtn }   from './MagneticBtn'
export { ScrollReveal }  from './ScrollReveal'
export { VideoScrub }    from './VideoScrub'
export { WatchCanvas }   from './WatchCanvas'
export { WatchTiltCard } from './WatchTiltCard'
export { HeroSkeleton }  from './Skeleton'
export { LoadingScreen } from './LoadingScreen'
export { ScrollToTop }   from './ScrollToTop'
